export const SHELLS = ['bash', 'zsh', 'powershell'] as const;
export type Shell = (typeof SHELLS)[number];

export const TARGET_TOOLS = [
  'claude',
  'opencode',
  'kiro',
  'copilot',
  'factory',
  'openhands',
] as const;

export type TargetTool = (typeof TARGET_TOOLS)[number];

export const ANCHOR_START = '# <<< CAESAR NATIVE-LIKE WRAPPER START >>>';
export const ANCHOR_END = '# <<< CAESAR NATIVE-LIKE WRAPPER END >>>';

export function generateBashZshWrapper(tool: TargetTool): string {
  let matchConditions = '';

  if (tool === 'claude') {
    matchConditions = `  if [ "$1" = "plugin" ] && [ "$2" = "marketplace" ] && [ "$3" = "add" ] && [ -n "$4" ]; then
    caesar add "$4" --tool claude
  elif [ "$1" = "plugin" ] && [ "$2" = "install" ] && [ -n "$3" ]; then
    caesar add "$3" --tool claude`;
  } else if (tool === 'opencode') {
    matchConditions = `  if [ "$1" = "subagent" ] && [ "$2" = "add" ] && [ -n "$3" ]; then
    caesar add "$3" --tool opencode
  elif [ "$1" = "subagent" ] && [ "$2" = "remove" ] && [ -n "$3" ]; then
    caesar remove "$3"`;
  } else if (tool === 'kiro' || tool === 'openhands') {
    matchConditions = `  if [ "$1" = "agent" ] && [ "$2" = "install" ] && [ -n "$3" ]; then
    caesar add "$3" --tool ${tool}`;
  } else if (tool === 'copilot' || tool === 'factory') {
    matchConditions = `  if [ "$1" = "agent" ] && [ "$2" = "add" ] && [ -n "$3" ]; then
    caesar add "$3" --tool ${tool}`;
  }

  return `${tool}() {
${matchConditions}
  else
    if ! command -v ${tool} >/dev/null 2>&1; then
      echo "Error: The underlying command '${tool}' was not found in PATH." >&2
      return 1
    fi
    command ${tool} "$@"
  fi
}`;
}

export function generatePowerShellWrapper(tool: TargetTool): string {
  let matchConditions = '';

  if (tool === 'claude') {
    matchConditions = `    if ($args[0] -eq "plugin" -and $args[1] -eq "marketplace" -and $args[2] -eq "add" -and $args[3]) {
        caesar add $args[3] --tool claude
    } elseif ($args[0] -eq "plugin" -and $args[1] -eq "install" -and $args[2]) {
        caesar add $args[2] --tool claude
    }`;
  } else if (tool === 'opencode') {
    matchConditions = `    if ($args[0] -eq "subagent" -and $args[1] -eq "add" -and $args[2]) {
        caesar add $args[2] --tool opencode
    } elseif ($args[0] -eq "subagent" -and $args[1] -eq "remove" -and $args[2]) {
        caesar remove $args[2]
    }`;
  } else if (tool === 'kiro' || tool === 'openhands') {
    matchConditions = `    if ($args[0] -eq "agent" -and $args[1] -eq "install" -and $args[2]) {
        caesar add $args[2] --tool ${tool}
    }`;
  } else if (tool === 'copilot' || tool === 'factory') {
    matchConditions = `    if ($args[0] -eq "agent" -and $args[1] -eq "add" -and $args[2]) {
        caesar add $args[2] --tool ${tool}
    }`;
  }

  return `function ${tool} {
${matchConditions} else {
        $realBin = (Get-Command ${tool} -All -ErrorAction SilentlyContinue | Where-Object { $_.CommandType -ne 'Function' -and $_.CommandType -ne 'Alias' } | Select-Object -First 1).Path
        if (-not $realBin) {
            Write-Error "The underlying command '${tool}' was not found in PATH."
            return
        }
        & $realBin @args
    }
}`;
}

export function generateFullScript(shell: Shell): string {
  const wrappers = TARGET_TOOLS.map((tool) => {
    if (shell === 'powershell') {
      return generatePowerShellWrapper(tool);
    }
    return generateBashZshWrapper(tool);
  }).join('\n\n');

  return `${ANCHOR_START}
# Caesar Native-Like CLI Wrappers
# Automatically generated by 'caesar alias'. Do not modify manually.
${wrappers}
${ANCHOR_END}`;
}
